# Generated by Django 4.0.4 on 2022-04-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='destination',
            name='place',
            field=models.CharField(max_length=180),
        ),
    ]
