# Generated by Django 4.0.4 on 2022-04-21 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_alter_destination_city_alter_destination_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='created_at',
        ),
    ]
